#!/usr/bin/env bash
set -euo pipefail

# One-shot automation helper:
# 1) Optional auto-commit
# 2) Push current branch to origin
# 3) Create PR via GitHub CLI (or update if already exists)
#
# Prereqs:
#   - git remote origin configured
#   - gh CLI installed and authenticated (`gh auth status`)
#
# Usage examples:
#   bash scripts/cpu/sbatch/auto/push_and_create_pr.sh
#   AUTO_COMMIT=1 COMMIT_MSG="Update utah2023 sbatch" bash scripts/cpu/sbatch/auto/push_and_create_pr.sh
#   BASE_BRANCH=main PR_TITLE="Fix Utah 2023 prepare" bash scripts/cpu/sbatch/auto/push_and_create_pr.sh

BASE_BRANCH=${BASE_BRANCH:-main}
AUTO_COMMIT=${AUTO_COMMIT:-0}
COMMIT_MSG=${COMMIT_MSG:-"chore: automated update"}
PR_TITLE=${PR_TITLE:-"Automated update from $(git rev-parse --abbrev-ref HEAD)"}
PR_BODY=${PR_BODY:-"Auto-generated by scripts/cpu/sbatch/auto/push_and_create_pr.sh"}

if ! command -v git >/dev/null 2>&1; then
  echo "[ERROR] git not found" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "[ERROR] gh CLI not found. Install GitHub CLI first." >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "[ERROR] gh is not authenticated. Run: gh auth login" >&2
  exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ -z "${BRANCH}" ]]; then
  echo "[ERROR] failed to detect current branch" >&2
  exit 1
fi

if [[ "${AUTO_COMMIT}" == "1" ]]; then
  if [[ -n "$(git status --porcelain)" ]]; then
    git add -A
    git commit -m "${COMMIT_MSG}"
    echo "[INFO] committed local changes"
  else
    echo "[INFO] no local changes to commit"
  fi
fi

echo "[STEP] push branch: ${BRANCH}"
git push -u origin "${BRANCH}"

# Check if PR from this branch already exists.
EXISTING_PR_URL=$(gh pr list --head "${BRANCH}" --base "${BASE_BRANCH}" --json url --jq '.[0].url' 2>/dev/null || true)

if [[ -n "${EXISTING_PR_URL}" && "${EXISTING_PR_URL}" != "null" ]]; then
  echo "[INFO] PR already exists: ${EXISTING_PR_URL}"
  echo "[STEP] updating PR title/body"
  gh pr edit "${EXISTING_PR_URL}" --title "${PR_TITLE}" --body "${PR_BODY}"
  echo "[DONE] PR updated: ${EXISTING_PR_URL}"
else
  echo "[STEP] creating PR: ${BRANCH} -> ${BASE_BRANCH}"
  gh pr create --base "${BASE_BRANCH}" --head "${BRANCH}" --title "${PR_TITLE}" --body "${PR_BODY}"
  echo "[DONE] PR created"
fi